/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controladores.ProveedoresCtrl;
import javax.swing.JOptionPane;

/**
 *
 * @author Tiris
 */
public class ProveedoresForm extends javax.swing.JDialog {
    
    private ProveedoresCtrl ctrl;
    /**
     * Creates new form ProveedoresForm
     */
    public ProveedoresForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        ctrl = new ProveedoresCtrl();
        initComponents();
        setTitle("Agregar Nuevo Proveedor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FormularioProveedoresPanel = new javax.swing.JPanel();
        lblTienda = new javax.swing.JLabel();
        lblTienda1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTienda = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        FooterPanel = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FormularioProveedoresPanel.setBackground(new java.awt.Color(153, 204, 255));

        lblTienda.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        lblTienda.setText("Nombre de la Tienda:");

        lblTienda1.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        lblTienda1.setText("Status:");

        lblNombre1.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        lblNombre1.setText("Nombre:");

        cbStatus.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        javax.swing.GroupLayout FormularioProveedoresPanelLayout = new javax.swing.GroupLayout(FormularioProveedoresPanel);
        FormularioProveedoresPanel.setLayout(FormularioProveedoresPanelLayout);
        FormularioProveedoresPanelLayout.setHorizontalGroup(
            FormularioProveedoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormularioProveedoresPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(FormularioProveedoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTienda)
                    .addComponent(lblNombre1)
                    .addComponent(lblTienda1))
                .addGroup(FormularioProveedoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormularioProveedoresPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FormularioProveedoresPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(FormularioProveedoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTienda)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        FormularioProveedoresPanelLayout.setVerticalGroup(
            FormularioProveedoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormularioProveedoresPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(FormularioProveedoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre1))
                .addGap(18, 18, 18)
                .addGroup(FormularioProveedoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTienda)
                    .addComponent(txtTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FormularioProveedoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTienda1)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(FormularioProveedoresPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 160));

        FooterPanel.setBackground(new java.awt.Color(102, 153, 255));

        btnCancelar.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FooterPanelLayout = new javax.swing.GroupLayout(FooterPanel);
        FooterPanel.setLayout(FooterPanelLayout);
        FooterPanelLayout.setHorizontalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterPanelLayout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        FooterPanelLayout.setVerticalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(FooterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 400, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Limpiar y Cerrar modal 
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (txtNombre.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un nombre para el proveedor");
            txtNombre.requestFocus();
            return;
        }
        if (txtTienda.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un nombre de la tienda del proveedor'");
            txtTienda.requestFocus();
            return;
        }

        // SI PASO LAS VALIDACIONES
        String status;
        if (cbStatus.getSelectedIndex() == 0) {
            status = "OK";
        }else{
            status = "des";
        }
        
        ctrl.llenarModelo(txtNombre.getText(), txtTienda.getText(), status);
        
        if (ctrl.add()){
            JOptionPane.showMessageDialog(this, "Proveedor agregado correctamente");
            //mostrar("");
        } else{
            JOptionPane.showMessageDialog(this, "Proveedor NO agregado, intentalo más tarde");
        }
        
        dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProveedoresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProveedoresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProveedoresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProveedoresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProveedoresForm dialog = new ProveedoresForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FooterPanel;
    private javax.swing.JPanel FormularioProveedoresPanel;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblTienda;
    private javax.swing.JLabel lblTienda1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTienda;
    // End of variables declaration//GEN-END:variables
}
